# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EchoDesk < Formula
  desc "Local-first proof desk for reviewing code written by coding agents"
  homepage "https://github.com/sidkhuntia/echo"
  version "0.3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sidkhuntia/echo/releases/download/v0.3.0/echo-desk_0.3.0_darwin_amd64.tar.gz"
      sha256 "e9cc9948df1c1ac2960d675e97aaccbd0b58fe04be3433770cce4e2040fb226e"

      define_method(:install) do
        bin.install "echo-desk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sidkhuntia/echo/releases/download/v0.3.0/echo-desk_0.3.0_darwin_arm64.tar.gz"
      sha256 "af4bb44dc9bc26e969c5ca2b17d240f74e58398ea3c7b84ab7d13125949a1e6b"

      define_method(:install) do
        bin.install "echo-desk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sidkhuntia/echo/releases/download/v0.3.0/echo-desk_0.3.0_linux_amd64.tar.gz"
      sha256 "1744839a212780d9e06adbd1a23de927f6a48c809bcf3f4e8e16c4784f197051"
      define_method(:install) do
        bin.install "echo-desk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sidkhuntia/echo/releases/download/v0.3.0/echo-desk_0.3.0_linux_arm64.tar.gz"
      sha256 "822550749d5bf608c8e004d768355dc2d8e89fbb896d104fc773cc49cebbeba5"
      define_method(:install) do
        bin.install "echo-desk"
      end
    end
  end

  test do
    assert_match "echo", shell_output("#{bin}/echo-desk -version")
  end
end
