# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EchoDesk < Formula
  desc "Local-first proof desk for reviewing code written by coding agents"
  homepage "https://github.com/sidkhuntia/echo"
  version "0.0.2"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/sidkhuntia/echo/releases/download/v0.0.2/echo-desk_0.0.2_darwin_amd64.tar.gz"
    sha256 "d0ce5e7c3a9965a4a6b5b22d1b30b59f553f2625e9c371ac467670a7dbc5ebaf"

    define_method(:install) do
      bin.install "echo-desk"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/sidkhuntia/echo/releases/download/v0.0.2/echo-desk_0.0.2_darwin_arm64.tar.gz"
    sha256 "249bb6b97de418c76786c5f6a92900f5707cda808a306993ce8a222af6005f67"

    define_method(:install) do
      bin.install "echo-desk"
    end
  end

  test do
    assert_match "echo", shell_output("#{bin}/echo-desk -version")
  end
end
