# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rune < Formula
  desc "AI-powered Git commit message generator"
  homepage "https://github.com/sidkhuntia/rune"
  version "2.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sidkhuntia/rune/releases/download/v2.1.0/rune-darwin-amd64.tar.gz"
      sha256 "09f7dd2a54e14d3922552a0795f9281d7643c216d411ef3c4810d981812708c3"

      def install
        bin.install "rune"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sidkhuntia/rune/releases/download/v2.1.0/rune-darwin-arm64.tar.gz"
      sha256 "ed149ce3ca8347d310000b46b90068a920cf7697fb148ca5b14a33c7222f58e2"

      def install
        bin.install "rune"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sidkhuntia/rune/releases/download/v2.1.0/rune-linux-amd64.tar.gz"
      sha256 "e0ef9ac9ee8d75bc9681886c16c71479f094d83f09eae38bca73bcda4e8f5174"
      def install
        bin.install "rune"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sidkhuntia/rune/releases/download/v2.1.0/rune-linux-arm64.tar.gz"
      sha256 "926810a2e5ba7157088e885a17f64509f7184d2fdca78c68565238ebdf3365ea"
      def install
        bin.install "rune"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/rune --version")
  end
end
